#!/bin/bash

set -euo pipefail

if command -v zsh >/dev/null; then
  sudo chsh -s $(command -v zsh) $USER
fi

CHEZMOI_PATH="$(command -v chezmoi)"
MISE_PATH="$(command -v mise)"

if command -v chezmoi >/dev/null; then
  chezmoi -- chezmoi init --apply --source $PWD
  exit
fi

if command -v mise >/dev/null; then
  mise exec chezmoi -- chezmoi init --apply --source $PWD
  exit
fi

sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --source $PWD
exit

exit 1
