#!/bin/bash

set -euxo pipefail

if command -v zsh >/dev/null; then
  sudo chsh -s $(command -v zsh) $USER
fi

if command -v mise >/dev/null; then
  mise exec chezmoi -- chezmoi apply --source $PWD
  exit 0
fi

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- apply --source $PWD
  exit 0
fi

exit 1
