min_version = "2025.11.7"

[tools]
bat = "0.26.1"
difftastic = "0.69.0"
doggo = "1.2.0"
fd = "10.4.2"
fzf = "0.74.2"
github-cli = "2.97.0"
"github:neovim/neovim" = "0.12.0"
"github:nushell/nushell" = { version = "0.114.1", exe = "nu" }
"github:peteonrails/voxtype" = { version = "0.7.5", asset_pattern = "voxtype-*-linux-x86_64-vulkan" }
"github:twpayne/chezmoi" = "2.70.0"
herdr = "0.8.0"
jj = "0.44.0"
lsd = "1.2.0"
node = "24.18.0"
ripgrep = "15.2.0"
starship = "1.26.0"
zellij = "0.44.3"

[settings]
experimental = true
lockfile = true
pin = true
minimum_release_age = "7d"

[env]
'_'.path = ["~/.cargo/bin"]
'_'.file = { path = ".envrc" }
